JBEHAVE-1407 Expand TableParsers API to parse examples table as string into pojo
vividus-framework/jbehave-core pull request #3
Opened 2020-05-19 19:00 UTC by uarlouski

2020-05-19 19:16 UTC, valfirst requested changes

2020-05-19 19:16 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTable.java
> +    public static final class ParsedExamplesTable {
`ParsedExamplesTableData`

2020-05-19 19:16 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTable.java
> +    private static <T> void replaceCollection(Collection<T> target, Collection<T> replacement) {
I wouldn't extract this method, readability is getting worse

2020-05-20 12:08 UTC, uarlouski commented
In master https://github.com/vividus-framework/jbehave-core/commit/1b3a8ae647e55767159f3894ede90cd1bc7ff199

2020-05-20 12:08 UTC, closed without merging