[jbehave-core] add ignore/comment logic into addComposedStep() method
vividus-framework/jbehave-core pull request #4
Opened 2020-07-15 07:50 UTC by VitaliLebedzeu

Change if block's variables in addComposedSteps() method and ignore/comment logic to addComposedStep() method

2020-07-15 14:04 UTC, valfirst requested changes

2020-07-15 14:04 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/steps/StepCandidate.java
> +            if (comment(composedStep)) {
`} else if (comment(composedStep)) {`

2020-07-15 14:09 UTC, VitaliLebedzeu commented on jbehave-core/src/main/java/org/jbehave/core/steps/StepCandidate.java
> +            if (comment(composedStep)) {
My fail... will be fixed.

2020-07-15 14:09 UTC, VitaliLebedzeu commented on jbehave-core/src/main/java/org/jbehave/core/steps/StepCandidate.java
> +            if (comment(composedStep)) {
fixed

2020-07-15 19:19 UTC, uarlouski commented on jbehave-core/src/test/java/org/jbehave/core/steps/CompositeCandidateStepsBehaviour.java
> +        @When("When ignore me")
just @When("ignore me")

2020-07-15 19:19 UTC, uarlouski approved these changes

2020-07-16 08:03 UTC, VitaliLebedzeu commented on jbehave-core/src/test/java/org/jbehave/core/steps/CompositeCandidateStepsBehaviour.java
> +        @When("When ignore me")
fixed

2020-07-16 14:08 UTC, valfirst commented
This fix was merged to `master` branch of upstream repository

2020-07-16 14:08 UTC, closed without merging